In [7]:
import tensorflow as tf
import tflearn
import numpy as np

### One Hot Vector

data 변수값에는 다음과 같이 들어가 있습니다.
```python
data = [0, 1, 2, 3, 4.7, 4.1]
```
예제에서 one_hot() 함수는 data에 해당하는 index에 7을 넣고, 나머지는 0을 넣습니다. <br>
중요하게 볼 부분은 4.7 이나 4.1 둘다 동일하게 4로 취급됩니다.

In [34]:
x = tf.placeholder('int64', [None], name='x')
x_one_hot = tf.one_hot(x, 10, 7., 0., name='x_one_hot')
tf.one_hot?

In [44]:
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    
    data = [0, 1, 2, 3, 4.7, 4.1]
    print sess.run(x_one_hot, feed_dict={x: data})

[[ 7.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  7.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  7.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  7.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  7.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  7.  0.  0.  0.  0.  0.]]
