In [2]:
import numpy as np
from keras.preprocessing.sequence import pad_sequences

### pad_sequences


* **sequences**: List of lists of int or float.
* **maxlen**: None or int. Maximum sequence length, longer sequences are truncated and shorter sequences are padded with zeros at the end.
* **dtype**: datatype of the Numpy array returned.
* **padding**: 'pre' or 'post', pad either before or after each sequence.
* **truncating**: 'pre' or 'post', remove values from sequences larger than maxlen either in the beginning or in the end of the sequence
* **value**: float, value to pad the sequences to the desired value.

sequences 를 받으면 (sample갯수, timesteps 갯수) shape을 갖은 2D Numpy array를 리턴합니다. 

### 3 dimensions -> 10 dimensions with 'pre' padding

In [5]:
data = np.array([[1,2,3], [4,5,6]])
pad_sequences(data, maxlen=10)

array([[0, 0, 0, 0, 0, 0, 0, 1, 2, 3],
       [0, 0, 0, 0, 0, 0, 0, 4, 5, 6]], dtype=int32)

### 3 dimensions -> 10 dimensions with 'post' padding

In [6]:
data = np.array([[1,2,3], [4,5,6]])
pad_sequences(data, maxlen=10, padding='post')

array([[1, 2, 3, 0, 0, 0, 0, 0, 0, 0],
       [4, 5, 6, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

### Truncate (10 -> 3) with pre option

In [13]:
data = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 
                 [20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])
pad_sequences(data, maxlen=3, truncating='pre')

array([[ 7,  8,  9],
       [12, 11, 10]], dtype=int32)

### Truncate (10 -> 3) with post option

In [12]:
data = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 
                 [20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])
pad_sequences(data, maxlen=3, truncating='post')

array([[ 0,  1,  2],
       [20, 19, 18]], dtype=int32)