# 1D Convolution (Signal)

* http://www.cs.cornell.edu/courses/cs1114/2013sp/sections/S06_convolution.pdf

## Definition




In [1]:
%pylab inline
import numpy as np
import torch

from torch import nn 
from torch.autograd import Variable

Populating the interactive namespace from numpy and matplotlib


In [29]:
def create_conv(kernel, bias=None, in_channels=1, out_channels=1):
    kernel_size = kernel.shape[-1]
    kernel_ts = torch.FloatTensor(kernel)
    if bias:
        bias_ts = torch.FloatTensor(bias)
    else:
        bias_ts = torch.FloatTensor(np.zeros([1]))
    
    conv_f = torch.nn.Conv1d(1, 1, kernel_size, stride=1)
    conv_f.register_parameter('weight', torch.nn.Parameter(kernel_ts))
    conv_f.register_parameter('bias', torch.nn.Parameter(bias_ts))
    return conv_f

def conv(conv_f, inputs):
    inputs_ts = Variable(torch.FloatTensor(inputs))
    return conv_f(inputs_ts).data.numpy()

In [30]:
x = np.array([[[[1, 2, 3, 0], 
               [0, 1, 2, 3], 
               [3, 0, 1, 2],
               [2, 3, 0, 1]]]], dtype='float64')


kernel = np.array([[[[2, 0, 1], 
                    [0, 1, 2], 
                    [1, 0, 2]]]], dtype='float64')


conv_f = create_conv(kernel)
conv(conv_f, x).shape

(1, 1, 2, 3)

In [31]:
_weight, _bias = list(conv_f.parameters())

print(_weight.data.numpy())
print(_bias.data.numpy())

[[[[ 2.  0.  1.]
   [ 0.  1.  2.]
   [ 1.  0.  2.]]]]
[ 0.]


In [ ]:
class Conv(object):
    def __init__(self, w, b, stride=1, pad=0):
    self.w = 

# References

### Convolution
* [Convolution - Cornell](http://www.cs.cornell.edu/courses/cs1114/2013sp/sections/S06_convolution.pdf)
* [Basic Filters](http://www.swarthmore.edu/NatSci/mzucker1/e27/filter-slides.pdf)

### CNN

* [Using Convolutional Neural Networks for Image Recognition](https://ip.cadence.com/uploads/901/cnn_wp-pdf)
* [CS231n Convolutional Neural Networks for Visual Recognition](http://cs231n.github.io/convolutional-networks/)
* [Convolutional Neural Networks (CNNs): An Illustrated Explanation](http://xrds.acm.org/blog/2016/06/convolutional-neural-networks-cnns-illustrated-explanation/)
* [Convolutional Neural Networks backpropagation: from intuition to derivation](https://grzegorzgwardys.wordpress.com/2016/04/22/8/)
* [Notes on Convolutional Neural Networks - MIT](http://cogprints.org/5869/1/cnn_tutorial.pdf)


### implementation

* [Convnet: Implementing Convolution Layer with Numpy](http://wiseodd.github.io/techblog/2016/07/16/convnet-conv-layer/)
* [How convolutional neural networks see the world - Keras](https://blog.keras.io/how-convolutional-neural-networks-see-the-world.html)