In [1]:
import numpy as np
import tensorflow as tf

In [16]:
X = tf.Variable([[1,2,3], [4,5,6], [7,8,9]])
Y = tf.Variable(5)
T = tf.Variable([0, 0, 1])

s = tf.add(X, Y, name='sum')


In [21]:
init_var_op = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init_var_op)
    
    print 'X + Y' 
    print sess.run( tf.add(X, Y, name='sum') )
    
    print 
    print 'X + T'
    print sess.run(tf.add(X, T))

X + Y
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

X + T
[[ 1  2  4]
 [ 4  5  7]
 [ 7  8 10]]
