# Transposed Convolution 

Transposed convolution은 일반적인 convolution의 연산의 반대로 transformation을 할때 사용을 합니다.<br>


In [2]:
%pylab inline
import numpy as np
from scipy import signal as sg

Populating the interactive namespace from numpy and matplotlib


In [82]:
image = np.array([[3, 3, 2, 1, 0], 
                  [0, 0, 1, 3, 1], 
                  [3, 1, 2, 2, 3],
                  [2, 0, 0, 2, 2],
                  [2, 0, 0, 0, 1]])
kernel = np.array([[0, 1, 2], 
                   [2, 2, 0], 
                   [0, 1, 2]])
output = sg.correlate2d(image, kernel, mode='valid')
print(output)



[[12 12 17]
 [10 17 19]
 [ 9  6 14]]


In [80]:
image = np.array([[3, 3, 2], 
                  [0, 0, 1], 
                  [3, 1, 2]])

kernel = np.array([[0, 1, 1], 
                   [0, 0, 0], 
                   [1, 0, 0]])
# kernel = np.array([[0, 1, 2], 
#                    [2, 2, 0], 
#                    [0, 1, 2]])
output = sg.correlate2d(kernel, image, mode='valid')
print(output)

print(image * kernel)
print( (image * kernel).sum())

[[8]]
[[0 3 2]
 [0 0 0]
 [3 0 0]]
8


In [ ]:
sg.deconvolve()