In [2]:
import tensorflow as tf 
import numpy as np

# Convert To Tensor 

tf.convert_to_tensor(value, dtype=None, name=None, preferred_dtype=None)

### Example

In [6]:
def foo(arg):
    arg = tf.convert_to_tensor(arg, dtype='float32')
    return tf.matmul(arg, arg) + arg

v1 = foo(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
v2 = foo([[1.0, 2.0], [3.0, 4.0]])
v3 = foo(np.array([[1.0, 2.0], [3.0, 4.0]]))

In [12]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.4, allow_growth=True)
with tf.Session(config=tf.ConfigProto(gpu_options=gpu_options)) as sess:
    r1, r2, r3 = sess.run([v1, v2, v3])
    
    print(r1, end='\n\n')
    print(r2, end='\n\n')
    print(r3, end='\n\n')

[[  8.  12.]
 [ 18.  26.]]

[[  8.  12.]
 [ 18.  26.]]

[[  8.  12.]
 [ 18.  26.]]

