In [80]:
import tensorflow as tf
import numpy as np

from pprint import pprint as pp

## Create a Interactive Session

In [7]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.01, allow_growth=True)
sess = tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))

## tf.slice(input_, begin, size, name=None)

begin vector 가 예를 들어서 [0, 0, 1] 이고, size vector가 [1, 2, 3] 이라면 다음과 같은 slice을 하게 됩니다. 

> data[0:0+1, 0:0+2, 1:1+3]

In [59]:
data = np.array([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])


s1 = tf.slice(data, [1, 0, 0], [1, 1, 3])
s2 = tf.slice(data, [1, 0, 0], [1, 2, 3])
s3 = tf.slice(data, [1, 0, 0], [2, 1, 3])

print('S1')
print(s1.eval())
print(data[1:1+1, 0:0+1, 0:0+3])

print('\nS2')
print(s2.eval())
print(data[1:1+1, 0:0+2, 0:0+3])

print('\nS3')
print(s3.eval())
print('-------------')
print(data[1:1+2, 0:0+1, 0:0+3])

S1
[[[3 3 3]]]
[[[3 3 3]]]

S2
[[[3 3 3]
  [4 4 4]]]
[[[3 3 3]
  [4 4 4]]]

S3
[[[3 3 3]]

 [[5 5 5]]]
-------------
[[[3 3 3]]

 [[5 5 5]]]


## tf.split(value, num_or_size_splits, axis=0, num=None, name='split')

In [205]:
data = np.arange(5*30).reshape((5, 30))
print('Data')
print(data)

splitted1 = tf.split(data, [4, 15, 11], axis=1)

print('\nSplitted 01')
print(tf.shape(splitted1[0]).eval()) # 4
print(splitted1[0].eval())

print('\nSplitted 02')
print(tf.shape(splitted1[1]).eval()) # 15
print(splitted1[1].eval())

print('\nSplitted 03')
print(tf.shape(splitted1[2]).eval()) # 11
print(splitted1[2].eval())

Data
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
   48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
  108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139 140 141 142 143 144 145 146 147 148 149]]

Splitted 01
[5 4]
[[  0   1   2   3]
 [ 30  31  32  33]
 [ 60  61  62  63]
 [ 90  91  92  93]
 [120 121 122 123]]

Splitted 02
[ 5 15]
[[  4   5   6   7   8   9  10  11  12  13  14  15  16  17  18]
 [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78]
 [ 94  95  96  97  98  99 100 101 102 103 10

In [203]:
splitted = tf.split(data, [1, 2, 2], axis=0)

print('\n\nSplitted 01')
print('Shape:', tf.shape(splitted[0]).eval())
print(splitted[0].eval())
print('numpy')
print(data[0:1])

print('\n\nSplitted 02')
print('Shape:', tf.shape(splitted[1]).eval())
print(splitted[1].eval())
print('numpy')
print(data[1:3])

print('\n\nSplitted 03')
print('Shape:', tf.shape(splitted[2]).eval())
print(splitted[2].eval())
print('numpy')
print(data[3:5])



Splitted 01
Shape: [ 1 30]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29]]
numpy
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29]]


Splitted 02
Shape: [ 2 30]
[[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
  54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
  84 85 86 87 88 89]]
numpy
[[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
  54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
  84 85 86 87 88 89]]


Splitted 03
Shape: [ 2 30]
[[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
  108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139 140 141 142 143 144 145 146 147 148 149]]
numpy
[[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 