In [1]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


# Softmax Classifier

* http://cs231n.github.io/linear-classify/#softmax 참고 
* https://eli.thegreenplace.net/2016/the-softmax-function-and-its-derivative/


Softmax function은 N-dimensional vector를 받아서 다시 N-dimensional vector로 return을 합니다. <br>
이때 output은 0~1 사이의 확률분포를 갖으며, 전체의 합은 1이 됩니다. $ S(a) : \mathbb{R}^{\mathbb{N}} \rightarrow \mathbb{R}^{\mathbb{N}} $

각각의 element단위의 공식은 다음과 같습니다. 

$$ S_i = \frac{e^{x_i}}{\sum^N_{k=1} e^{x_k}} $$

$ S_i $ 는 exponent연산을 하기 때문에 항상 positive 값을 갖습니다.<br>
또한 numerator부분이 denominator에서 합쳐져서 나오기 때문에  0~1 사이의 확률분포로 값이 나오게 됩니다.

# Derivative of softmax

## Example 1

아래 예제에서 `[1.0, 2.0, 3.0]` 은 softmax함수에 의해서 `[0.09, 0.24, 0.67]` 로 transform되어야 하며, 합은 1이 되어야 합니다.

In [2]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x/np.sum(exp_x, axis=0)

a = [1, 2, 3]
b = softmax(a)

print('value    :', a)
print('softmax  :', b)
print('summed up:', np.sum(b))

value    : [1, 2, 3]
softmax  : [ 0.09003057  0.24472847  0.66524096]
summed up: 1.0


## Example 2

* [Udacity - Softmax](https://classroom.udacity.com/courses/ud730/lessons/6370362152/concepts/63815621490923#)

1번정답 <br>
```
[ 0.09003057  0.24472847  0.66524096]
```

2번정답<br>
```
[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]
```

In [3]:
scores1 = np.array([1.0, 2.0, 3.0])
scores2 = np.array([[1, 2, 3, 6],
                    [2, 4, 5, 6], 
                    [3, 8, 7, 6]])

def softmax(x):
    exp_x = np.exp(x)
    return exp_x/np.sum(exp_x, axis=0)

# plot(scores1, softmax(scores1))
print(softmax(scores2), np.sum(softmax(scores2)))

[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]] 4.0
