# Numpy 101 

In [77]:
%pylab inline
import numpy as np
from IPython.display import display

Populating the interactive namespace from numpy and matplotlib


### Arrays

np.array( iterable ) 형태로 사용하며 iterable은 Python에서 list같은 iterate를 돌수 있는 형태를 말합니다.

In [63]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [13]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Shape

In [16]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [15]:
a = np.array([[[1], [2], [3]], [[4], [5], [6]]])
a.shape

(2, 3, 1)

### Range

range(start, end, step)

In [17]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

### Sum, Mean, Max, Min

In [65]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print('sum:', a.sum())
print('mean:', a.mean())
print('max:', a.max())
print('min:', a.min())
print('len:', len(a))

sum: 55
mean: 5.5
max: 10
min: 1
len: 10


### Indexing 

array[index] 처럼 zero-based indexing을 사용하여 array안의 element에 접근 가능

In [33]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[0], a[1], a[2], a[3], a[4], a[-1]

(1, 2, 3, 4, 5, 10)

In [45]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a[0, 0]) # A_{0,0} 과 같음
print(a[0, 1])
print(a[0, 2])
print(a[0, 3])
print(a[1, 0])
print(a[1, 1])
print(a[1, 2])
print(a[1, 3])

1
2
3
4
5
6
7
8


In [55]:
# : 는 전체를 선택한다는 뜻
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a[:, 0]) 
print(a[:, 1])
print(a[:, 2])
print(a[:, 3])

[1 5]
[2 6]
[3 7]
[4 8]


In [62]:
# 범위를 선택
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a[0, :1])
print(a[0, :2])
print(a[0, :3])
print(a[0, :4])
print(a[1, :1])
print(a[1, :2])
print(a[1, :3])
print(a[1, :4])

[1]
[1 2]
[1 2 3]
[1 2 3 4]
[5]
[5 6]
[5 6 7]
[5 6 7 8]


# Linear Algebra

### Vector & Basic operations

기본적으로 array와 동일

In [79]:
a = np.array([1, 2, 3, 4]) # Vector A 
b = np.array([0, 1, 2, 0]) # Vector B

print('sum:     \t', a + b)
print('multiply:\t', a * b)
print('division:\t', b / a)
print

sum:     	 [1 3 5 4]
multiply:	 [0 2 6 0]
division:	 [ 0.          0.5         0.66666667  0.        ]
