# Transposed Convolution 

Transposed convolution은 일반적인 convolution의 연산의 반대로 transformation을 할때 사용을 합니다.<br>
대부분 Deconvolution으로 알고 있지만, 잘못된 표현입니다. 예를 들어서 auto encoder를 하게 될때, Encoder에서 black box를 통해 convolution을 하게 됩니다. 이후 Decoder부분에서는 다시 black box를 통해서 deconvolution을 하게 됩니다. 이경우 원래 input image의 spatial resolution (공간적 모양 - 픽셀의 양) 로 black box를 통해 돌아가는 것이므로 deconvolution이라는 표현이 맞습니다. 
(Deconvolution은 수학적 연산이라기 보다는 input으로 사용된 spatial resolution 돌아가는 개념정도로 이해하는게 좋을듯 합니다)

Transposed convolution은 deconvolution과 마찬가지로 동일한 spatial resolution으로 돌아가기 때문입니다.<br>
다른점은 수학적으로 연산하는 방법 자체가 다릅니다.<br>
Transposed convolution은 일반적인 convolution과 동일하지만 spatial transformation을 반대로 합니다.

## No zero padding, unit strides

In [2]:
%pylab inline
import numpy as np
from scipy import signal as sg

Populating the interactive namespace from numpy and matplotlib


In [82]:
image = np.array([[3, 3, 2, 1, 0], 
                  [0, 0, 1, 3, 1], 
                  [3, 1, 2, 2, 3],
                  [2, 0, 0, 2, 2],
                  [2, 0, 0, 0, 1]])
kernel = np.array([[0, 1, 2], 
                   [2, 2, 0], 
                   [0, 1, 2]])
output = sg.correlate2d(image, kernel, mode='valid')
print(output)

[[12 12 17]
 [10 17 19]
 [ 9  6 14]]


In [80]:
image = np.array([[3, 3, 2], 
                  [0, 0, 1], 
                  [3, 1, 2]])

kernel = np.array([[0, 1, 1], 
                   [0, 0, 0], 
                   [1, 0, 0]])
# kernel = np.array([[0, 1, 2], 
#                    [2, 2, 0], 
#                    [0, 1, 2]])
output = sg.correlate2d(kernel, image, mode='valid')
print(output)

print(image * kernel)
print( (image * kernel).sum())

[[8]]
[[0 3 2]
 [0 0 0]
 [3 0 0]]
8


In [ ]:
sg.deconvolve()