# strided_slice

```
tf.strided_slice(input_, begin, end, strides=None, begin_mask=0, end_mask=0, ellipsis_mask=0, new_axis_mask=0, shrink_axis_mask=0, var=None, name=None)
```

begin과 end사이의 데이터를 extract합니다.

In [2]:
import tensorflow as tf
import numpy as np

### Create InteractiveSession

In [5]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.001, allow_growth=True)
sess = tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))
init_op = tf.global_variables_initializer()
sess.run(init_op)

### Data

In [25]:
data = np.array([[[1.1, 1.2, 1.3], [2.1, 2.2, 2.3]], 
                 [[3.1, 3.2, 3.3], [4.1, 4.2, 4.3]], 
                 [[5.1, 5.2, 5.3], [6.1, 6.2, 6.3]]])
inputs = tf.convert_to_tensor(data)
sess.run(inputs)

array([[[ 1.1,  1.2,  1.3],
        [ 2.1,  2.2,  2.3]],

       [[ 3.1,  3.2,  3.3],
        [ 4.1,  4.2,  4.3]],

       [[ 5.1,  5.2,  5.3],
        [ 6.1,  6.2,  6.3]]])

### Examples (using begin and end)

In [26]:
sliced1 = tf.strided_slice(inputs, begin=[0], end=[3])
sess.run(sliced1)

array([[[ 1.1,  1.2,  1.3],
        [ 2.1,  2.2,  2.3]],

       [[ 3.1,  3.2,  3.3],
        [ 4.1,  4.2,  4.3]],

       [[ 5.1,  5.2,  5.3],
        [ 6.1,  6.2,  6.3]]])

In [38]:
sliced1 = tf.strided_slice(inputs, begin=[1, 0], end=[3, 1])
sess.run(sliced1)

array([[[ 3.1,  3.2,  3.3]],

       [[ 5.1,  5.2,  5.3]]])

In [45]:
sliced1 = tf.strided_slice(inputs, begin=[1, 0], end=[3, 2])
sess.run(sliced1)

array([[[ 3.1,  3.2,  3.3],
        [ 4.1,  4.2,  4.3]],

       [[ 5.1,  5.2,  5.3],
        [ 6.1,  6.2,  6.3]]])

In [46]:
sliced1 = tf.strided_slice(inputs, begin=[1, 0, 0], end=[3, 1, 1])
sess.run(sliced1)

array([[[ 3.1]],

       [[ 5.1]]])

In [61]:
sliced1 = tf.strided_slice(inputs, begin=[0, 0, 0], end=[3, 1, -1])
sess.run(sliced1)

array([[[ 1.1,  1.2]],

       [[ 3.1,  3.2]],

       [[ 5.1,  5.2]]])

In [64]:
sliced1 = tf.strided_slice(inputs, begin=[0, 0, 0], end=[-1, 1, 1])
sess.run(sliced1)

array([[[ 1.1]],

       [[ 3.1]]])

### Examples (using strides)

strides 값이 모두 1값을 갖은 vector라면.. 안쓴거와 동일합니다.

In [94]:
sliced1 = tf.strided_slice(inputs, begin=[0, 0, 0], end=[2, 1, 3])
print('no strides')
print(sess.run(sliced1))

sliced1 = tf.strided_slice(inputs, begin=[0, 0, 0], end=[2, 1, 3], strides=[1, 1, 1])
print('\nstride used')
print(sess.run(sliced1))

no strides
[[[ 1.1  1.2  1.3]]

 [[ 3.1  3.2  3.3]]]

stride used
[[[ 1.1  1.2  1.3]]

 [[ 3.1  3.2  3.3]]]


In [108]:
sliced1 = tf.strided_slice(inputs, begin=[0, 0, 0], end=[3, 1, 3], strides=[2, 1, 2])
print(sess.run(sliced1))

[[[ 1.1  1.3]]

 [[ 5.1  5.3]]]
