In [1]:
import tensorflow as tf
import numpy as np

In [4]:
init_op = tf.global_variables_initializer()
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.001, allow_growth=True)
sess = tf.InteractiveSession(config=tf.ConfigProto(gpu_options=gpu_options))
sess.run(init_op)

In [3]:
data = np.array([[[1, 2, 3, 4]], 
                 [[5, 6, 7, 8]], 
                 [[0, 10, 20, 30]]])

(3, 1, 4)

In [20]:
inputs = tf.placeholder('float32', shape=(None, None, 4))
mean1 = tf.reduce_mean(inputs)
mean2 = tf.reduce_mean(inputs, reduction_indices=[0])
mean3 = tf.reduce_mean(inputs, reduction_indices=[1])
mean4 = tf.reduce_mean(inputs, reduction_indices=[2])
mean5 = tf.reduce_mean(inputs, reduction_indices=[1, 2])

init_op = tf.global_variables_initializer()
sess.run(init_op)

sess.run([mean1, mean2, mean3, mean4, mean5], feed_dict={inputs: data})

[8.0,
 array([[  2.,   6.,  10.,  14.]], dtype=float32),
 array([[  1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  0.,  10.,  20.,  30.]], dtype=float32),
 array([[  2.5],
        [  6.5],
        [ 15. ]], dtype=float32),
 array([  2.5,   6.5,  15. ], dtype=float32)]

## reduce_mean(inputs)

그냥 reduce_mean 사용시, 전체 elements들의 평균을 구합니다. <br>
다음과 동일합니다. 
$$ \frac{1+2+3+4+5+6+7+8+10+20+30}{12} $$

In [13]:
data.mean()

8.0

In [14]:
sess.run(mean1, feed_dict={inputs: data})

8.0

## reduce_mean(inputs, reduction_indices=[0])

columns들의 평균을 구합니다. 

In [15]:
data.mean(axis=0)

array([[  2.,   6.,  10.,  14.]])

In [16]:
sess.run(mean2, feed_dict={inputs: data})

array([[  2.,   6.,  10.,  14.]], dtype=float32)

## reduce_mean(inputs, reduction_indices=[2])

rows의 평균을 구합니다.

In [17]:
data.mean(axis=2)

array([[  2.5],
       [  6.5],
       [ 15. ]])

In [18]:
sess.run(mean4, feed_dict={inputs: data})

array([[  2.5],
       [  6.5],
       [ 15. ]], dtype=float32)

## reduce_mean(inputs, reduction_indices=[1, 2])

In [25]:
data.mean(axis=2).mean(axis=1)

array([  2.5,   6.5,  15. ])

In [26]:
sess.run(mean5, feed_dict={inputs: data})

array([  2.5,   6.5,  15. ], dtype=float32)